# netlify.toml

[build]
  # Directory where the React build output is located
  publish = "dist"
  command = "npm run build"

[[redirects]]
  # Redirect all routes to index.html
  from = "/*"
  to = "public/index.html"
  status = 200
